version: '3'

services:
  gate_db:
    image: mysql:8
    container_name:
      gate_db
    volumes:
      - ./gate_mysql/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gate
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "3306:3306"
  gate:
    build:
      context: .
      dockerfile: Docker_Gate
    command: python ./gate_code/manage.py runserver 0.0.0.0:8000
    container_name:
      gate
    volumes:
      - .:/gate_code
    environment:
      - PLAY_FLG=1
    ports:
      - "8000:8000"
    depends_on:
      - gate_db
      - observe
      - world
    links:
      - gate_db
      - observe
      - world
  observe:
    build:
      context: .
      dockerfile: Docker_Observe
    command: python ./observe_code/manage.py runserver 0.0.0.0:8000
    container_name:
      observe
    volumes:
      - .:/observe_code
    expose:
      - "8000"
    depends_on:
      - world_db
    links:
      - world_db
  world:
    build:
      context: .
      dockerfile: Docker_World
    command: python ./world_code/manage.py runserver 0.0.0.0:8000
    container_name:
      world
    volumes:
      - .:/world_code
    expose:
      - "8000"
    depends_on:
      - world_db
    links:
      - world_db
  world_db:
    image: mysql:8
    container_name:
      world_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=world
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    expose:
      - "3306"
