version: '3'

services:
  gate_db:
    image: mysql:8
    container_name:
      gate_db
    volumes:
      - ./gate_mysql/mysql_data:/var/lib/mysql
      - ./gate_mysql/mysql_conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gate
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    expose:
      - "3306"
  gate:
    build:
      context: .
      dockerfile: Docker_Gate
    container_name:
      gate
    command:  bash -c "
        python ./gate_code/mysql_connection_check.py &&
        python ./gate_code/manage.py migrate &&
        python ./gate_code/manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/gate_code
    environment:
      - PLAY_FLG=1
    ports:
      - "8000:8000"
    depends_on:
      - gate_db
      - observe
      - world
    links:
      - gate_db
      - observe
      - world
  observe:
    build:
      context: .
      dockerfile: Docker_Observe
    container_name:
      observe
    command:  bash -c "
        python ./observe_code/mysql_connection_check.py &&
        python ./observe_code/manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/observe_code
    expose:
      - "8000"
    depends_on:
      - world_db
    links:
      - world_db
  world:
    build:
      context: .
      dockerfile: Docker_World
    container_name:
      world
    command: bash -c "
        python ./world_code/mysql_connection_check.py &&
        python ./world_code/manage.py migrate &&
        sh ./world_code/snitch_activate.sh &&
        python ./world_code/manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/world_code
    expose:
      - "8000"
    depends_on:
      - world_db
    links:
      - world_db
  world_db:
    image: mysql:8
    container_name:
      world_db
    volumes:
      - ./world_mysql/mysql_conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=world
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    expose:
      - "3306"
